services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-strong}
      POSTGRES_DB: ${POSTGRES_DB:-fastship}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data_shipment:/var/lib/postgresql/data

volumes:
  postgres_data_shipment:
